name: Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build all targets
      run: dotnet build --configuration Release --no-restore
      
    - name: Run tests
      run: dotnet test WikitextParser.Tests --configuration Release --no-build --verbosity normal

    - name: Pack NuGet Package
      run: dotnet pack WikitextParser/WikitextParser.csproj --configuration Release --output ${{ github.workspace }}/nuget_packages --no-build

    - name: Upload Artifact
      if: steps.pack.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: WikitextParser-Package
        path: ${{ github.workspace }}/nuget_packages/*.nupkg
        if-no-files-found: error
